# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2017-07-05 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KksDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks', models.CharField(default='kks', max_length=15, verbose_name='kks\u7f16\u53f7')),
                ('loc_gz', models.CharField(choices=[('ggq', '\u9ad8\u8fc7\u524d'), ('gzq', '\u9ad8\u518d\u524d'), ('gzh', '\u9ad8\u518d\u540e')], max_length=5, verbose_name='\u70df\u6e29\u63a2\u9488\u4f4d\u7f6e')),
                ('loc_umd', models.CharField(choices=[('up', '\u4e0a'), ('mid', '\u4e2d'), ('down', '\u4e0b')], max_length=15, verbose_name='\u9ad8\u5ea6')),
                ('loc_ab', models.CharField(choices=[('a', '\u5de6\u4fa7'), ('b', '\u53f3\u4fa7')], max_length=5, verbose_name='\u5de6\u53f3\u4fa7')),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(blank=True, max_length=1400, null=True, verbose_name='\u6d4b\u91cf\u6e29\u5ea6')),
                ('case_time', models.DateTimeField(verbose_name='\u6d4b\u91cf\u5de5\u51b5\u65f6\u95f4')),
                ('kks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas.KksDesc', verbose_name='kks\u7f16\u53f7')),
            ],
        ),
    ]
