# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2017-08-02 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kksdesc',
            options={'verbose_name': '\u6d4b\u70b9KKS', 'verbose_name_plural': '\u6d4b\u70b9KKS'},
        ),
        migrations.AlterModelOptions(
            name='temp',
            options={'verbose_name': '\u6d4b\u70b9\u6e29\u5ea6', 'verbose_name_plural': '\u6d4b\u70b9\u6e29\u5ea6'},
        ),
    ]
