# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2017-08-02 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0002_auto_20170802_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='temp',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='\u6d4b\u91cf\u6e29\u5ea6'),
        ),
    ]
