# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2017-10-23 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpansionKks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks', models.CharField(default='kks', max_length=15, verbose_name='\u81a8\u80c0\u6307\u793a\u5668KKS')),
                ('location', models.CharField(default='\u6c34\u51b7\u58c1', max_length=20, verbose_name='\u81a8\u80c0\u6307\u793a\u5668\u4f4d\u7f6e')),
                ('ab', models.CharField(choices=[('right', '\u53f3\u4fa7'), ('left', '\u5de6\u4fa7')], max_length=10, verbose_name='\u5de6\u53f3\u4fa7')),
                ('vector', models.CharField(choices=[('x', 'X\u65b9\u5411'), ('y', 'Y\u65b9\u5411'), ('z', 'Z\u65b9\u5411')], max_length=5, verbose_name='\u65b9\u5411')),
            ],
            options={
                'verbose_name': '\u81a8\u80c0\u6307\u793a\u5668\u63cf\u8ff0',
                'verbose_name_plural': '\u81a8\u80c0\u6307\u793a\u5668\u63cf\u8ff0',
            },
        ),
        migrations.CreateModel(
            name='MeasureValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='\u5b9e\u6d4b\u81a8\u80c0\u91cf')),
            ],
            options={
                'verbose_name': '\u81a8\u80c0\u5b9e\u6d4b\u503c',
                'verbose_name_plural': '\u81a8\u80c0\u5b9e\u6d4b\u503c',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_time', models.DateTimeField(verbose_name='\u6d4b\u91cf\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u81a8\u80c0\u6d4b\u91cf\u65f6\u95f4',
                'verbose_name_plural': '\u81a8\u80c0\u6d4b\u91cf\u65f6\u95f4',
            },
        ),
        migrations.AddField(
            model_name='measurevalue',
            name='case_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expansion.Time', verbose_name='\u6d4b\u91cf\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='measurevalue',
            name='kks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expansion.ExpansionKks', verbose_name='\u81a8\u80c0\u6307\u793a\u5668KKS'),
        ),
    ]
