# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2017-10-24 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expansion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansionkks',
            name='ab',
            field=models.CharField(choices=[('right', '\u53f3\u4fa7'), ('left', '\u5de6\u4fa7'), ('middle', '\u4e2d\u90e8')], max_length=10, verbose_name='\u5de6\u53f3\u4fa7'),
        ),
    ]
