# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2017-10-25 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expansion', '0002_auto_20171024_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurevalue',
            name='case_time',
            field=models.DateTimeField(verbose_name='\u6d4b\u91cf\u65f6\u95f4'),
        ),
    ]
